name: Node CI (Windows)

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest removed due yet unknown SIGSEGV error
        os: [windows-latest]
        node-version: [16.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm i
          npm test
        env:
          CI: true
